version: '3'

services:
    #api
    black-key:
      build:
        context: .
        dockerfile: ./Dockerfile
        args:
          - WORKSPACE=${WORKSPACE}
      restart: always
      env_file:
        - .env
      volumes:
        - ./storage/log:/${WORKSPACE}/storage/log
        - ./storage/upload:/${WORKSPACE}/storage/upload
      ports:
        - ${APP_PORT}:80
      networks:
        - backend

    #socketio
    # socketio:
    #   build:
    #     context: .
    #     dockerfile: ./Dockerfile.socketio
    #     args:
    #       - WORKSPACE=socketio
    #   restart: always
    #   volumes:
    #     - ${DATA_PATH_HOST}/socketio/${APP_NAME}/upload:/socketio/upload
    #     - ${DATA_PATH_HOST}/socketio/${APP_NAME}/log:/socketio/log
    #   networks:
    #     - backend
networks:
  backend:
    external: true